name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.2.0

        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}

          script: |
            cd ${{ secrets.DEPLOY_PATH }}

            if [ ! -d ".git" ]; then
              git clone https://github.com/Suzven/Idea-Finder.git .
            else
              git fetch origin
              git reset --hard origin/main
            fi